### ISSUE TITLE
Ugly stacktrace logged if the GeneNames service is unavailable

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1434]
```
net.sf.json.JSONException: Invalid JSON String
        at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:143) ~[json-lib-2.4-jdk15.jar:na]
        at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:103) ~[json-lib-2.4-jdk15.jar:na]
        at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:84) ~[json-lib-2.4-jdk15.jar:na]
        at org.phenotips.ontology.internal.GeneNomenclature.getInfo(GeneNomenclature.java:306) ~[ontology-hgnc-access-api-1.0.jar:na]
        at org.phenotips.ontology.internal.GeneNomenclature.getVersion(GeneNomenclature.java:292) ~[ontology-hgnc-access-api-1.0.jar:na]
        at org.phenotips.ontology.listeners.PatientOntologyVersionRecorder.getOntologiesVersions(PatientOntologyVersionRecorder.java:128) ~[ontology-access-api-1.0.jar:na]
....

**Comment by buske** [comment]
Could this explain many of the issues with saving that occur when the internet connection is slow or intermittent?
