### ISSUE TITLE
Last stable phenotips release does not work on Windows XP

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1851]
Downloaded phenotips-standalone-1.1.1 on Windows XP. After clicking on start.sh, the command prompt reported the folowing error:

```
Starting Jetty on port 8080, please wait...
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:473)
        at org.eclipse.jetty.start.Main.start(Main.java:615)
        at org.eclipse.jetty.start.Main.main(Main.java:96)
Caused by: java.lang.UnsupportedClassVersionError: org/phenotips/tools/jetty/lis
tener/NotifyListener : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.eclipse.jetty.util.Loader.loadClass(Loader.java:100)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.nodeClas
s(XmlConfiguration.java:366)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(X
mlConfiguration.java:767)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValu
e(XmlConfiguration.java:1141)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(Xm
lConfiguration.java:1044)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(Xml
Configuration.java:735)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configur
e(XmlConfiguration.java:400)
        at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configur
e(XmlConfiguration.java:355)
        at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.jav
a:296)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:12
62)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:119
7)
        ... 7 more

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information
Press any key to continue . . .
```

The same thing happened with phenotips-standalone-1.2-milestone-5.

--Orion

**Comment by sdumitriu** [comment]
The system doesn't have a recent Java version (at least Java 1.7 is required).

**Comment by marta-** [comment]
The standalone distribution should check if the requied java version is installed and, if not, display a user-friendly error message instead of throwing an exception.

**Comment by buske** [comment]
@marta- Hmm, the system java version says that it is up-to-date. I looked and it was running Java 1.6. Does that mean we do not support Microsoft XP?

**Comment by marta-** [comment]
Microsoft doesn't support Microsoft XP... AFAIK Java 8 works just fine on Windows XP, but might need to be installed manually.
